---
title: "Pano-Tacana Phylogeny - First Report"
output: html_document
date: '2022-07-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Map of all varieties

```{r cars, include=FALSE}
library(rcldf)
library(ggrepel)
library(rnaturalearth)
library(rnaturalearthdata)
library(raster)
library(tidyverse)

zariquieypano <- cldf('../../cldf/cldf-metadata.json')
languages <- zariquieypano$tables$LanguageTable


map_sa <- ne_countries(continent = c("south america"), scale = "medium", returnclass = "sf")
sf_oceans <- ne_download(type = "ocean", category = "physical", return = "sf")
rivers <- ne_download(category = 'physical', type = 'rivers_lake_centerlines', returnclass = "sf", scale = 10)

rst <- ne_download(scale = 10, type = 'NE1_LR_LC_SR_W_DR', category = 'raster', destdir = "./map_data/")

hills <- raster("./map_data/NE1_LR_LC_SR_W_DR.tif")
hills_df <- as.data.frame(hills, xy = T) %>% 
  filter(x >= -85,
         x <= -60,
         y <= 1,
         y >= -30)

map_pt <- ggplot() +
  geom_sf(data = map_sa) +
  geom_raster(data = hills_df, aes(x=x, y=y, fill= NE1_LR_LC_SR_W_DR)) +
  geom_sf(data = sf_oceans) +
  coord_sf(ylim=c(-15, -3), xlim= c(-82, -62)) + 
  scale_fill_gradient(low = "grey20", high = "grey70") +
  
  geom_point(data = languages,
             aes(Longitude, Latitude),
             size = 5,
             shape = 22,
             color = "black",
             fill = "red") +
  
  geom_label_repel(box.padding = 1,
                   point.padding = 0.3,
                   data = languages, aes(Longitude, Latitude, label=Name), 
                   size = 4,
                   max.overlaps = 99) +
  labs(#caption = "Data: Glottolog",
       y = "",
       x = "",
       title = "Map of Pano-Tacana languages in zariquieypano") +
  theme(legend.position="none")
```

```{r}
map_pt
```

```{r}
library('ggplot2')
library('ggtree')
library('treeio')
library('RColorBrewer')
library('tidyverse')

# Trees
tree <- read.beast('pano_2_withoutRoot/pano_mrca.tree')

# CAheight_0.95_HPD

tree@data['CAheight_0.95_HPD'] <- sprintf("%f", as.numeric(tree@data[['CAheight_0.95_HPD']]))
tree@data['CAheight_0.95_HPD'][tree@data['CAheight_0.95_HPD'] == 'NA',] <- NA


tree@data['rposterior'] <- sprintf("%0.2f", as.numeric(tree@data[['posterior']]))
tree@data['rposterior'][tree@data['rposterior'] == 'NA',] <- NA

cls <- list(
  'Bolivian Nawa' = c("Pakawara", "Chakobo"),
  "Chama + Kakataibo" = c("Kapanawa", "ShipiboKonibo", "Kakataibo"),
  "Headwaters Pano" = c("Sharanawa", "Marinawa", "Mastanawa", "Yaminawa", 
                        "Nawa", "Chaninawa", "Yawanawa", "Shanenawa", 
                        "KashinawaP", "KashinawaB", "Amawaka", "Arara"),
  #'Kakataibo' = "Kakataibo",
  "Kaxarari" = "Kaxarari",
  'Marubo' = c("Katukina", "Kanamari", "Marubo"),
  'Matis-Matses' = c("Matses", "Matis"),
  "Poyanawa" = c("Nukini", "Iskonawa", "Poyanawa")
)


tree <- groupOTU(tree, cls, overlap="origin", connect=FALSE)

print(levels(attr(tree@phylo, 'group')))
colors <- c(
    "#333333", # 0  - i.e. non colored branches.
    "#fdae61", # Bolivian Nawa
    "#a6d96a",  # Chama
    "#006837",  # Headwaters Pano
    #"#fee08b",   # Kakataibo
    "#f46d43",  # Kaxarari
    "#66bd63",    # Marubo
    "#a50026",    # Matis-Matses    
    "#1a9850"    # Poyanawa
)


tree_pt <- ggtree(tree, aes(color=group), 
            ladderize=TRUE, size=1.5) %>% 
    revts() + 
  geom_tiplab(align=TRUE, linesize=2) +
  geom_label(
    aes(label=rposterior), 
    label.size=1.2, na.rm=TRUE, size=4.5,
    nudge_x=-9, nudge_y=0
    ) +
    theme_tree2() +
    scale_color_manual(values=colors) +
    scale_x_continuous(breaks = c(), limits=c(-2440, 770)) +

  theme(legend.position="none")

col_idx = 2
for (clade in levels(attr(tree@phylo, 'group'))) {
    if (is.null(cls[[clade]])) next
    m <- MRCA(tree, cls[[clade]])
    if (!is.null(m)) {
        cat(paste(clade, m, col_idx, colors[col_idx]), "\n")
        tree_pt <- tree_pt + geom_cladelabel(
            node=m, label=clade, color = colors[col_idx],
            extend=0.4, # extending the bars up/down

            offset=400,  # bars from node?
            offset.text=50, # offset of text from labels
            # General
            barsize=2
            )
    }
    col_idx <- col_idx + 1
}
tree_pt
```


̄̄
```{r}
tree_pt
ggsave('pano_2_withoutRoot/pano_2_MRCA_withoutRoot.png', tree_pt, width=14, height=10)
```

Problematic traces: 